// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl8LAOBEVzZEBvqSbSUHbr5cRcdeJjtxM',
    appId: '1:994858440199:web:db55be7649e97a777d3ca2',
    messagingSenderId: '994858440199',
    projectId: 'manufacturing-monitor-0508',
    authDomain: 'manufacturing-monitor-0508.firebaseapp.com',
    storageBucket: 'manufacturing-monitor-0508.firebasestorage.app',
    measurementId: 'G-FHZ48NQW8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANp5kyeTnnxxeSRrVevwa258SRJJQLJF0',
    appId: '1:994858440199:android:cfe5ba3d9a20732c7d3ca2',
    messagingSenderId: '994858440199',
    projectId: 'manufacturing-monitor-0508',
    storageBucket: 'manufacturing-monitor-0508.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFtn-9Mkft0PHAnJBPc_hYGFM9sJPnJ4I',
    appId: '1:994858440199:ios:c6f122b56a599c037d3ca2',
    messagingSenderId: '994858440199',
    projectId: 'manufacturing-monitor-0508',
    storageBucket: 'manufacturing-monitor-0508.firebasestorage.app',
    iosBundleId: 'com.example.manufacturingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFtn-9Mkft0PHAnJBPc_hYGFM9sJPnJ4I',
    appId: '1:994858440199:ios:c6f122b56a599c037d3ca2',
    messagingSenderId: '994858440199',
    projectId: 'manufacturing-monitor-0508',
    storageBucket: 'manufacturing-monitor-0508.firebasestorage.app',
    iosBundleId: 'com.example.manufacturingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl8LAOBEVzZEBvqSbSUHbr5cRcdeJjtxM',
    appId: '1:994858440199:web:08096c84711243647d3ca2',
    messagingSenderId: '994858440199',
    projectId: 'manufacturing-monitor-0508',
    authDomain: 'manufacturing-monitor-0508.firebaseapp.com',
    storageBucket: 'manufacturing-monitor-0508.firebasestorage.app',
    measurementId: 'G-9DXLBMSRG3',
  );
}
